spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: user
      password: Root8818.
      url: jdbc:mysql://39.107.234.188/springcloud?characterEncoding=utf-8&useSSL=false

dev:
  dev

