spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: user
      password: Root8818.
      url: jdbc:mysql://39.107.234.188/springcloud?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379

dev:
  git-demo2

girl:
  name: haha
  age: 17
