spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: user
    password: Root8818.
    url: jdbc:mysql://39.107.234.188:3306/springcloud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 39.107.234.188
    port: 5672
    username: guest
    password: guest
